[package]
name = "tecio"
version = "0.1.0"
authors = ["Nanopro <nanopro1g@gmail.com>"]
edition = "2018"
build = "build.rs"
description = "Rust simple binding for Tecplot tecio library."
license = "GPL-3.0"

[dependencies]
libc = "*"